[pytest]
addopts = -s -v

python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: все ui тесты
    smoke: маркировка для smoke-тестов
    regression: маркировка для regression-тестов
    critical: маркировка для критичных тестов
    registration: маркировка для тестов, относящиеся к регистрации
    authorization: маркировка для тестов, относящиеся к авторизации
    slow: маркировка для slow-тестов
