from enum import Enum

class AllureTag(str, Enum):
    REGRESSION = 'REGRESSION'
    SMOKE = 'SMOKE'
    COURSES = "COURSES"
    DASHBOARD = "REGRESSION"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"
    REGISTRATION = "REGISTRATION"
    AUTHORIZATION = "AUTHORIZATION"

